---

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: use custom action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./actions/
